version: '3.8'
services:
  api:
    build: .
    container_name: youtube-tutorial-chat-mongodb-client-frontend
    ports:
      - '2024:3000'
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true
    tty: true 